### ISSUE TITLE
Error: WordPress files seem to already be present here.

### ISSUE THREAD

**Issue by dortamiguel** [sloansparger/webpack-wordpress#2]
When I run npm run setup I get this error:

Error: WordPress files seem to already be present here.

**Comment by sloansparger** [comment]
@ellipticaldoor Interesting... I will take a look tonight. @amphrony do you know anything about this?

**Comment by amphrony** [comment]
@sloansparger Yes.
@ellipticaldoor Remove directory, rebuild, and try again
`rm -r wordpress/`
`mkdir wordpress/`
Then run `npm run setup` again.

**Comment by sloansparger** [comment]
@ellipticaldoor I fixed the error you were seeing, you can follow what @amphrony said or just reclone the repo
