### ISSUE TITLE
Error with npm run build

### ISSUE THREAD

**Issue by skynet** [sloansparger/webpack-wordpress#4]
With a very basic css:
```
Module build failed:
body {
     ^
      Invalid CSS after "body {": expected "}", was "{"

```

**Comment by sloansparger** [comment]
@skynet thanks for letting me know! super busy with work right now, let me have a look at it this weekend.

**Comment by kohikudasai** [comment]
It uses Sass, if you want brackets, swap to scss-loader instead.
