### ISSUE TITLE
Testing on mobile

### ISSUE THREAD

**Issue by leonwatson2** [sloansparger/webpack-wordpress#7]
Hey I've connecting to my localhost computer to test my wp theme on mobile but it doesn't show me anything on load. Any ideas on how I can connect to it from an external source?

**Comment by sloansparger** [comment]
Thanks for reaching out. If you are trying to connect your mobile device, I typically do one of two things. I will visit the same port as my localhost but using the ip of my wifi network (make sure both devices connected, example: http://localhost:3000/ would become something similar http://192.123.1.143:3000).

Another option I usually go with is ngrok (https://ngrok.com/). This creates a publicly accessible url (example: http://<some-hash>.ngrok.io) that forwards to a port that you have running locally. Once you have it installed, just run `ngrok http <port-to-foward>` and copy the link generated. Any device in the world can now visit that port while you leave it running. 👍

Hope that helps! Also, looks like we live in the same town, would love to meet up sometime if you're interested.
